//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Microservices.ImageUploadService.ImageUploadService"/> </summary
    public sealed class ImageUploadServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ImageUploadServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "ImageUploadService";
            }
        }
        
        /// <summary>
        /// Call the UploadImage method on the ImageUploadService microservice
        /// <see cref="Microservices.ImageUploadService.ImageUploadService.UploadImage"/>
        /// </summary>
        public Beamable.Common.Promise<string> UploadImage(string filePath)
        {
            object raw_filePath = filePath;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("filePath", raw_filePath);
            return this.Request<string>("ImageUploadService", "UploadImage", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersImageUploadServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForImageUploadServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ImageUploadServiceClient>();
        }
        
        public static ImageUploadServiceClient ImageUploadService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ImageUploadServiceClient>();
        }
    }
}
