//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.ReferralService"/> </summary
    public sealed class ReferralServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ReferralServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "ReferralService";
            }
        }
        
        /// <summary>
        /// Call the CreateReferral method on the ReferralService microservice
        /// <see cref="Beamable.Microservices.ReferralService.CreateReferral"/>
        /// </summary>
        public Beamable.Common.Promise<string> CreateReferral()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("ReferralService", "CreateReferral", serializedFields);
        }
        
        /// <summary>
        /// Call the ClaimReferralReward method on the ReferralService microservice
        /// <see cref="Beamable.Microservices.ReferralService.ClaimReferralReward"/>
        /// </summary>
        public Beamable.Common.Promise<System.Threading.Tasks.Task> ClaimReferralReward(string referralCode)
        {
            object raw_referralCode = referralCode;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("referralCode", raw_referralCode);
            return this.Request<System.Threading.Tasks.Task>("ReferralService", "ClaimReferralReward", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersReferralServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForReferralServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ReferralServiceClient>();
        }
        
        public static ReferralServiceClient ReferralService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ReferralServiceClient>();
        }
    }
}
