//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;


    /// <summary> A generated client for <see cref="Beamable.Microservices.TournamentService"/> </summary
    public sealed class TournamentServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {

        public TournamentServiceClient(BeamContext context = null) :
                base(context)
        {
        }

        public string ServiceName
        {
            get
            {
                return "TournamentService";
            }
        }

        /// <summary>
        /// Call the SetScore method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.SetScore"/>
        /// </summary>
        public Beamable.Common.Promise<System.Threading.Tasks.Task> SetScore(string eventId, double score)
        {
            object raw_eventId = eventId;
            object raw_score = score;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("eventId", raw_eventId);
            serializedFields.Add("score", raw_score);
            return this.Request<System.Threading.Tasks.Task>("TournamentService", "SetScore", serializedFields);
        }

        /// <summary>
        /// Call the CheckOrCreatePayment method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.CheckOrCreatePayment"/>
        /// </summary>
        public Beamable.Common.Promise<System.Threading.Tasks.Task> CheckOrCreatePayment(string tournamentId)
        {
            object raw_tournamentId = tournamentId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("tournamentId", raw_tournamentId);
            return this.Request<System.Threading.Tasks.Task>("TournamentService", "CheckOrCreatePayment", serializedFields);
        }

        /// <summary>
        /// Call the HasUserPaidForTournament method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.HasUserPaidForTournament"/>
        /// </summary>
        public Beamable.Common.Promise<bool> HasUserPaidForTournament(string tournamentId)
        {
            object raw_tournamentId = tournamentId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("tournamentId", raw_tournamentId);
            return this.Request<bool>("TournamentService", "HasUserPaidForTournament", serializedFields);
        }

        /// <summary>
        /// Call the HasUserParticipated method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.HasUserParticipated"/>
        /// </summary>
        public Beamable.Common.Promise<bool> HasUserParticipated()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<bool>("TournamentService", "HasUserParticipated", serializedFields);
        }

        /// <summary>
        /// Call the GetUserActivities method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.GetUserActivities"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<Senet.Scripts.Models.PaymentModel>> GetUserActivities()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<System.Collections.Generic.List<Senet.Scripts.Models.PaymentModel>>("TournamentService", "GetUserActivities", serializedFields);
        }

        /// <summary>
        /// Call the CalculateReward method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.CalculateReward"/>
        /// </summary>
        public Beamable.Common.Promise<Senet.Scripts.Models.RewardModel> CalculateReward(float rotationAngle)
        {
            object raw_rotationAngle = rotationAngle;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("rotationAngle", raw_rotationAngle);
            return this.Request<Senet.Scripts.Models.RewardModel>("TournamentService", "CalculateReward", serializedFields);
        }

        /// <summary>
        /// Call the ClaimTournamentRewards method on the TournamentService microservice
        /// <see cref="Beamable.Microservices.TournamentService.ClaimTournamentRewards"/>
        /// </summary>
        public Beamable.Common.Promise<System.Threading.Tasks.Task> ClaimTournamentRewards(string eventId, string tournamentName, long amountWon, long rank)
        {
            object raw_eventId = eventId;
            object raw_tournamentName = tournamentName;
            object raw_amountWon = amountWon;
            object raw_rank = rank;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("eventId", raw_eventId);
            serializedFields.Add("tournamentName", raw_tournamentName);
            serializedFields.Add("amountWon", raw_amountWon);
            serializedFields.Add("rank", raw_rank);
            return this.Request<System.Threading.Tasks.Task>("TournamentService", "ClaimTournamentRewards", serializedFields);
        }
    }

    internal sealed class MicroserviceParametersTournamentServiceClient
    {

        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }

        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Double : MicroserviceClientDataWrapper<double>
        {
        }

        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Single : MicroserviceClientDataWrapper<float>
        {
        }

        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
    }

    [BeamContextSystemAttribute()]
    public static class ExtensionsForTournamentServiceClient
    {

        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<TournamentServiceClient>();
        }

        public static TournamentServiceClient TournamentService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<TournamentServiceClient>();
        }
    }
}
