using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Content;
using Beamable.Common;
using Beamable.Server;
using UnityEngine;

namespace Microservices.ImageUploadService
{
    [Microservice("ImageUploadService")]
    public class ImageUploadService : Microservice
    {
        [ConfigureServices]
        public static void Configure(IServiceBuilder builder)
        {
            builder.Builder.AddSingleton(p => new HttpClient());
            builder.Builder.AddSingleton<ContentUploader>();
            builder.Builder.AddSingleton<IContentApi, ContentApi>();
        }

        [ClientCallable]
        public async Task<string> UploadImage(string filePath, byte[] image, byte[] md5Byte)
        {
            try
            {
                var contentUploader = Provider.GetService<ContentUploader>();
                var hostedUrl = await contentUploader.UploadLocalImage(filePath, image, md5Byte);
                await UpdateProfileUrlStat(hostedUrl);
                return hostedUrl;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
        
        [ServerCallable]
        private async Task UpdateProfileUrlStat(string hostedUrl)
        {
            try
            {

                const string statKey = "ProfileUrl";
                const string access = "public";

                var stats = new Dictionary<string, string>
                {
                    { statKey, hostedUrl }
                };

                await Services.Stats.SetStats(access, stats);
            }
            catch (Exception e)
            {
                Debug.LogError($"Failed to update ProfileUrl stat. Exception: {e.Message}");
                throw;
            }
        }
    }
}