using System;
using System.Net.Http;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Content;
using Beamable.Common;
using Beamable.Server;
using UnityEngine;

namespace Microservices.ImageUploadService
{
    [Microservice("ImageUploadService")]
    public class ImageUploadService : Microservice
    {
        [ConfigureServices]
        public static void Configure(IServiceBuilder builder)
        {
            builder.Builder.AddSingleton(p => new HttpClient());
            builder.Builder.AddSingleton<ContentUploader>();
            builder.Builder.AddSingleton<IContentApi, ContentApi>();
        }

        [ClientCallable]
        public async Task<string> UploadImage(string filePath)
        {
            try
            {
                Debug.Log("hi");
                var contentUploader = Provider.GetService<ContentUploader>();
                var hostedUrl = await contentUploader.UploadLocalImage(filePath);
                return hostedUrl;
            }
            catch (Exception e)
            {
                System.Console.WriteLine(e);
                throw;
            }
        }
    }
}