using System;
using Beamable;
using Beamable.Player;
using TMPro;
using UnityEngine;
using System.Net.Http;
using Beamable.Api.Autogenerated.Content;
using UnityEngine.UI;

namespace Assets.Scripts
{
    public class ProfileManager : MonoBehaviour
    {
        private BeamContext _beamContext;
        private PlayerAccount _playerAccount;
        private ContentUploader _contentUploader;

        [Header("UI Text References")]
        [SerializeField]
        private TextMeshProUGUI usernameText;
        [SerializeField]
        private TextMeshProUGUI gidText;
        [SerializeField]
        private TextMeshProUGUI emailText;

        [Header("Profile Picture")]
        [SerializeField]
        private Image profileImage; 
        [SerializeField]
        private Button uploadButton;
        [SerializeField]
        private string localImagePath;
        private void Start()
        {
            InitializeBeamable();
            uploadButton.onClick.AddListener(OnUploadButtonClicked);
        }

        private async void InitializeBeamable()
        {
            try
            {
                _beamContext = await BeamContext.Default.Instance;
                await _beamContext.Accounts.OnReady;

                _playerAccount = _beamContext.Accounts.Current;

                var httpClient = new HttpClient();
                var contentApi = _beamContext.ServiceProvider.GetService<IContentApi>();
                _contentUploader = new ContentUploader(contentApi, httpClient);

                DisplayPlayerProfile();
            }
            catch (Exception ex)
            {
                Debug.LogError($"Failed to initialize Beamable: {ex.Message}");
            }
        }

        private void DisplayPlayerProfile()
        {
            if (_playerAccount != null)
            {
                var username = _playerAccount.Alias;
                var gid = _playerAccount.GamerTag.ToString();
                var shortenedGid = ShortenGamerTag(gid);
                var email = _playerAccount.Email ?? "Email not set";

                usernameText.text = username;
                gidText.text = shortenedGid;
                emailText.text = email;

                Debug.Log("Player profile loaded.");
            }
            else
            {
                Debug.LogError("Failed to retrieve player account information.");
                usernameText.text = "Not found";
                gidText.text = "Not found";
                emailText.text = "Not found";
            }
        }
        
        private void OnUploadButtonClicked()
        {
            Debug.Log("Profile picture clicked");
            NativeGallery.GetImageFromGallery((path) =>
            {
                if (!string.IsNullOrEmpty(path))
                {
                    localImagePath = path;
                    Debug.Log("Image selected: " + path);
                    UploadProfilePicture();
                }
                else
                {
                    Debug.LogWarning("No image selected");
                }
            });
        }

        /// <summary>
        /// Uploads the profile picture using the ContentUploader class.
        /// </summary>
        public async void UploadProfilePicture()
        {
            try
            {
                Debug.Log("Uploading profile picture...");
                var hostedUrl = await _contentUploader.UploadLocalImage(localImagePath);

                Debug.Log($"Profile picture uploaded successfully: {hostedUrl}");
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"Failed to upload profile picture: {ex.Message}");
            }
        }
        
      

        private string ShortenGamerTag(string gid)
        {
            if (string.IsNullOrEmpty(gid) || gid.Length <= 12)
            {
                return gid;
            }

            var firstPart = gid[..9];
            var lastPart = gid[^3..];

            return $"{firstPart}...{lastPart}";
        }
    }
}
